### ISSUE TITLE
[BUG] Video upload fails with "Read-only file system" error when video repair is triggered

### ISSUE THREAD

**Issue by bjornrun** [open-edge-platform/geti_v2#971]
### 🧩 Issue type

Bug 🐞

### 📄 Description

When uploading MP4 videos that require repair (e.g., corrupted or improperly encoded videos), the resource microservice fails with a "Read-only file system" error. This occurs in Kubernetes deployments where the storage volume is mounted as read-only.

### 📋 Steps to reproduce (if applicable)

1. Deploy Geti in a Kubernetes environment with read-only storage volumes (just run ./platform_installer install)
2. Upload an MP4 video that triggers the repair mechanism (e.g., a video with variable frame rate or corruption)
3. The upload fails with error 500

### 💻 Expected behavior

Upload video successful

### Error Details

```
2025-08-02 14:13:22,829 [WARNING ] [media_utils.video_file_repair:158] [trace_id=2bca660d305fe9e741788e2fe6546f47 span_id=3a36440935e1f09f resource.service.name=resource-microservice] [organization_id=5a251205-3188-44fc-a974-be72e97e0516 workspace_id=145fff0d-2296-470c-9fe9-ed10f40cdc76]: The video file at 688e1cf7627ef5250f046c10.mp4 is corrupt. Trying a repair
INFO:     127.0.0.6:50721 - "POST /api/v1/organizations/5a251205-3188-44fc-a974-be72e97e0516/workspaces/145fff0d-2296-470c-9fe9-ed10f40cdc76/projects/5a3fc5b9585864b22b72fbd6/datasets/5a3fc5b9585864b22b72fbdc/media/videos HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
  File "/interactive_ai/services/resource/app/resource_management/media_manager.py", line 694, in upload_video
    if not VideoFileRepair.check_and_repair_video(video_binary_repo=video_binary_repo, filename=binary_filename):
  File "/interactive_ai/services/resource/.venv/lib/python3.10/site-packages/media_utils/video_file_repair.py", line 161, in check_and_repair_video
    result = VideoFileRepair.attempt_repair(video_binary_repo=video_binary_repo, filename=filename)
  File "/interactive_ai/services/resource/.venv/lib/python3.10/site-packages/media_utils/video_file_repair.py", line 67, in attempt_repair
    temporary_file_path = video_binary_repo.create_path_for_temporary_file(filename=filename, make_unique=True)
OSError: [Errno 30] Read-only file system: '/disk_size/storage'
```

### Root Cause

The video repair process in `media_utils/video_file_repair.py` attempts to create temporary files in the same directory as the original video file. When the storage volume is mounted as read-only (common in production Kubernetes deployments), this operation fails.

The issue occurs in `LocalStorageClient.create_path_for_temporary_file()` method in `/interactive_ai/libs/iai_core_py/iai_core/repos/storage/local_storage.py`, which tries to create temporary files in the same directory structure as the source file.

### Proposed Fix

Modify the `create_path_for_temporary_file` method in `LocalStorageClient` to detect read-only filesystems and fall back to a writable temporary directory (e.g., `/tmp`).

Here's the recommended implementation:

```python
def create_path_for_temporary_file(self, filename: str, make_unique: bool) -> str:
    """
    Create a temporary file location that holds a relation to the file at the given URL in the workspace.
    If make_unique is set to true, the temporary filepath is guaranteed to be unique. If set to false, the path
    will be generated in such a way that re-generating the path returns the same URL.

    :param filename: Filename of the non-temporary file that the temporary file relates to
    :param make_unique: If set to true, make the temporary file unique.
    :return: Target filepath where a new temporary file can be created
    """
    local_path_for_file = os.path.join(self.base_path, filename)
    _, extension = os.path.splitext(filename)
    target_directory = os.path.dirname(local_path_for_file)
    
    # Use /tmp for temporary files if the target directory is not writable
    try:
        os.makedirs(target_directory, exist_ok=True)
        # Test if directory is writable by creating a test file
        test_file = os.path.join(target_directory, f".write_test_{os.getpid()}")
        try:
            with open(test_file, 'w') as f:
                f.write('test')
            os.unlink(test_file)
            use_tmp = False
        except (OSError, IOError):
            use_tmp = True
    except (OSError, IOError):
        use_tmp = True
    
    if use_tmp:
        target_directory = "/tmp"
    
    if make_unique:
        _, temporary_file_path = tempfile.mkstemp(suffix=extension, dir=target_directory)
    else:
        if use_tmp:
            # Include part of the original path in the temp filename to avoid conflicts
            safe_filename = filename.replace('/', '_').replace('\\', '_')
            base_name = os.path.join("/tmp", f"{safe_filename}_tmp")
            temporary_file_path = base_name + extension
        else:
            base_name, extension = os.path.splitext(local_path_for_file)
            temporary_file_path = base_name + "_tmp" + extension
    return temporary_file_path
```

### Alternative Solutions

1. **Environment Variable**: Add an environment variable (e.g., `VIDEO_REPAIR_TEMP_DIR`) to configure the temporary directory location
2. **Dedicated Volume**: Mount a writable volume specifically for temporary files during video processing
3. **Configuration Option**: Add a configuration parameter to specify whether the storage is read-only and handle accordingly

### Impact

- This issue affects all Kubernetes deployments where storage volumes are mounted as read-only
- Video uploads that require repair will fail without this fix
- The fix is backward compatible and will not affect deployments with writable storage

### Environment

- Geti deployment in K3s/Kubernetes
- Read-only storage volumes
- Resource microservice version: [current version]

### Workaround

As a temporary workaround, users can pre-process videos to ensure they don't require repair using:

```bash
ffmpeg -i input.mp4 -c:v libx264 -fps_mode cfr -c:a aac -movflags +faststart output.mp4

### 📦 Geti version

2.10.2

### Hardware

INTEL(R) XEON(R) PLATINUM 8592V, Intel(R) Data Center GPU Max 1100

### 🖥️ Operating System

Ubuntu 22.04

### Browser (if applicable)

Chrome

### Python Version (if relevant)

_No response_

### ➕ Additional context

_No response_

**Comment by leoll2** [comment]
Hi Bjorn, the bug looks very similar to #882, which has been already fixed in 2.11. Could you try to upgrade to the latest version?

> OSError: [Errno 30] Read-only file system: '/disk_size/storage'

**Comment by jcchr** [comment]
@bjornrun - could you check if in the 2.11 (or newer) version the error still exists (as Leo suggested)?

**Comment by piotrgrubicki** [comment]
No response, closing.
